name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false 
          submodules: true

      - name: Setup .NET (Install F# Support)
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build F# Project
        run: dotnet build

      - name: Publish F# Project
        run: dotnet publish -c Release -o dist

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
